// Generated by CoffeeScript 1.8.0
(function() {
  var apiProxy, currentAdminPath, currentPath, exp, express, proxy, httpProxy, path, webAccess, poe_port, proxicode_port, app_port, host;

  apiProxy = function(_poe_port,_proxicode_port, _host) {
    return function(req, res, next) {
      	
      if (req.host.match(new RegExp("^www.pacificoasis.com"))||
	  req.host.match(new RegExp("^pacificoasis.com"))) {
        proxy.web(req, res, {
          target: {
	     host:_host,
	     port: _poe_port,
	     xfwd: true
	  }
        });
      } 
      else if (req.host.match(new RegExp("^www.proxicode.cc"))||
	      req.host.match(new RegExp("^proxicode.cc"))) {
	proxy.web(req, res, {
          target: {
	     host:_host,
	     port: _proxicode_port,
	     xfwd: true
	  }
        });
      }
      else {
        next();
      }
    };
  };

  webAccess = function() {
    return function(req, res, next) {
      var p, vpath;
      if (req.url.match(new RegExp("^/admin/"))) {
        p = currentAdminPath + req.path.substring(6);
        if (path.existsSync(p)) {
          console.log("loading.. " + p);
          res.sendfile(p);
        } else {
          res.send("Thank you for your inquiry.");
        }
      } else {
        vpath = (req.path === "/" ? "/index.html" : path.resolve(req.path));
        if (path.existsSync(currentPath + vpath)) {
          console.log("loading.. " + vpath);
          res.sendfile(currentPath + vpath);
        } else {
          res.send("Thanks for your inquery.");
        }
      }
    };
  };

 
  host = "localhost";

  poe_port = 8000;

  proxicode_port = 8001;

  app_port = 9000;

  express = require("express");

  path = require("path");

  console.log("__dirname:" + __dirname);

  currentPath = path.resolve(__dirname, "..", "..", "./theta/trunk/app");

  currentAdminPath = path.resolve(__dirname, "..", "..", "./xi/trunk/app");

  console.log("currentPath:" + currentPath);

  exp = express();

  httpProxy = require("http-proxy");
  proxy = httpProxy.createProxyServer({});

  exp.configure(function() {
    exp.use(apiProxy(poe_port,proxicode_port,host));
    //exp.use(webAccess());
  });

  exp.listen(app_port);

  console.log("The application's listening on the port# " + app_port);

  process.on("uncaughtException", function(err) {
    console.log("Application exits. err: " + err);
  });

  process.on("SIGTERM", function(err) {
    console.log("Application killed successfully. err: " + err);
  });

}).call(this);
